### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by quazardous** [osy/XG_Mobile_Station#12]
Hi, ROG ally is now Linux friendly with bazzite, cachyos. Could you test the XGM eGPU with Linux ?

**Comment by osy** [comment]
I don't need to, it should work exactly the same as with XG Mobile

**Comment by quazardous** [comment]
Ok I misunderstood because I read in the doc there were some software driver tweak.
Thx

**Comment by pktiuk** [comment]
You can find answer also in this discussion https://github.com/osy/XG_Mobile_Station/discussions/11
