### ISSUE TITLE
Can the ROG Ally be equipped with two USB-C ports like the Ally X?

### ISSUE THREAD

**Issue by gaowanliang** [osy/XG_Mobile_Station#18]
To be honest, I think most people aren't very interested in using an eGPU with handheld devices, including myself. However, if it were possible to reverse-engineer the XG Mobile interface to provide USB-C functionality, I believe many people would be quite interested. Unfortunately, I have no knowledge of hardware. Is this feasible?

**Comment by moni11811** [comment]
Cost to build is around $200/5 + $100 for the cable + GPU and according to my testing it loses around 3% performance (when using a RTX 3070 Ti) vs desktop.

vs 2k, lower performance, and non-upgradeability makes this project (and OSY's work) the most valuable and high quality Ive seen on Github recently. 

If you have any other (non-constructive) criticisms an open issue is not the place - a reddit post or discussion thread is...

**Comment by gaowanliang** [comment]
我将将其转移到discussions

**Comment by moni11811** [comment]
Hey - I want to apologize I didn't mean to go off on you like that earlier - I skimmed through your description and missed your title.

For the Ally X you're better off purchasing ADT-UT3G or TH3P4G3 than trying to build your own... also the loss in performance/bandwidth is much higher than this protocol/Oculink (32GBPS vs 63GBPS).

**Comment by gaowanliang** [comment]
> Hey - I want to apologize I didn't mean to go off on you like that earlier - I skimmed through your description and missed your title.
> 
> For the Ally X you're better off purchasing ADT-UT3G or TH3P4G3 than trying to build your own... also the loss in performance/bandwidth is much higher than this protocol/Oculink (32GBPS vs 63GBPS).

No problem, my friend. I think I wasn't clear enough in my description. What I'm thinking is to convert the XMG interface on the first-generation Ally into a Type-C interface, just like the Ally X, which has two Type-C ports, as [discussed in this post](https://www.reddit.com/r/ROGAlly/comments/1d7xzga/xg_mobile_usb_c_adapter/). After all, using a graphics card docking station with a handheld device does seem a bit impractical, as it requires us to sit at a desk. So why not just use my desktop? However, if we could convert this interface into a Type-C port, I believe it could be more useful.

**Comment by moni11811** [comment]
Too much loss for one USB-C and not feasible for dual USB-C implementation...

Wait for TB5
