### ISSUE TITLE
VL822-QFN76 discontinued

### ISSUE THREAD

**Issue by cjb-eng** [osy/XG_Mobile_Station#6]
Tried to source parts for this design but JLCPCB has informed me that my order for the VL822-QFN76 was cancelled because the part is discontinued. Is there a suitable replacement, perhaps a more expensive alternative so I can complete the BOM and get this built?

**Comment by osy** [comment]
First of all, fyi there's been fixes to the board since v4 so make sure you're using the latest design. How many boards are you building? Last I saw there was still parts in stock.

**Comment by cjb-eng** [comment]
I'm only looking to produce a couple of units for bench testing. I believe I've downloaded the v0.4 posted as the latest but maybe that's where I've gone wrong - does that BOM not contain this obsolete component?

**Comment by osy** [comment]
There is no v0.4.1 which is not yet released. I've attached the files below.
[BOM-XG_Mobile_Dock.csv](https://github.com/user-attachments/files/16421498/BOM-XG_Mobile_Dock.csv)
[CPL-XG_Mobile_Dock.csv](https://github.com/user-attachments/files/16421499/CPL-XG_Mobile_Dock.csv)
[GERBER-XG_Mobile_Dock.zip](https://github.com/user-attachments/files/16421500/GERBER-XG_Mobile_Dock.zip)

I don't know why JLCPCB says it's discontinued. How are you buying it? I see there's 18 in stock right now.
<img width="838" alt="image" src="https://github.com/user-attachments/assets/3169708f-dc76-45fe-b700-b91d4a2a9c00">

**Comment by cjb-eng** [comment]
I'm just trying to order via JLCPCB parts. Posted a screen capture of my
order history below in case that's helpful. You can see my order for
VL822-QFN76 was cancelled - the other bom parts appear to have processed
fine. Where do you see there are 18 in stock? My view of the parts status
shows 0 in stock.

I'm wondering if this is a regional issue. I'm trying to place this order
from the US. Do you happen to be ordering from a different country?

**Comment by osy** [comment]
I don't see your screenshot but here's what I see in the bill of materials screen when ordering
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/bbc1af1a-431f-4181-bf8b-517ca625a978">
I clicked the search button then clicked on the only part and I see "People are selling their idle parts:"

**Comment by cjb-eng** [comment]
This is very strange. I attached a couple of PNGs hopefully those come
through. I definitely do not see any stock of that same part on their page.

I guess I'll follow-up with support and include your screen shot to
demonstrate others do find them in stock. If they won't sell the parts to
me, the least they can do is refund me the other parts as they're useless
to me if I can't source the VL822. And it showed stock when I placed the
order...

**Comment by osy** [comment]
FWIW, the dock still works without the USB hub. It's just that on the Ally, there's only one USB port so you can't connect anything without a hub.

**Comment by cjb-eng** [comment]
Ahh, good to know. In that case, I'll priced to have the board produced.
I'll come back here when support gets back to me.

**Comment by cjb-eng** [comment]
So JLCPCB support confirms the part status has become unavailable. And
looking at your screen grab now with fresh eyes, I  see you're looking at
the idle inventory of another JLCPCB customer that's trying to sell off the
excess inventory they bought on the website. I'd completely blew through
that detail and went straight to order direct from JLCPCB at the BOM
process stage. Adding to the confusion, if you perform a direct search of
that part outside of the BOM process using the part manager, it isn't
immediately obvious that there is idle stock. You need to click on the
listed component to right of the displayed part's link (don't click on the
part's link as that will navigate you away from the page) in the white
non-obvious area. Only then does a drop down appear showing idle parts
availability. Maybe others (unfamiliar with JLCPCB as I am) looking to do
their own build will find this info helpful. Anyhow, I went back and
secured those idle components to fulfill my BOM so I'm looking forward to
testing this out with a RTX2060 I have sitting on the shelf.

But once those remaining (now 16) idle components are sold off I gather the
only option is to have the assemblies built without the USB functionality
as you mention. Do you know if there is a drop-in replacement from a
different manufacturer (e.g. Realtek)?

**Comment by osy** [comment]
There's no drop in replacement, but I see a couple of options

1. You can [consign parts](https://jlcpcb.com/help/article/245-How-to-consign-parts-to-JLCPCB) and order it outside of JLCPCB.
2. You can design a new board around RTS5423 or USB7216C or similar ICs. They combine USB PD controller and USB hub so you can get rid of the TI PD controller as well. Maybe the combined cost will be cheaper.
3. You can remove both the PD and hub controller and pass through the USB-C directly to a USB-C port. You will only get a single USB-C port and you can attach an external hub.

**Comment by cjb-eng** [comment]
Great thanks for the thoughts. Good reason for me to pickup KiCAD
